export const App = {
	TOGGLE_THEME: 'APP_TOGGLE_THEME',
};
export const User = {
	SET: 'SET_USER',
	SET_LOADING: 'SET_USER_LOADING',
};
export const Todo = {
	SET: 'SET_TODOS',
	SET_LOADING: 'SET_TODOS_LOADING',
	SET_CURRENT_TODO: 'SET_CURRENT_TODO',
	SET_CURRENT_TODO_LOADING: 'SET_CURRENT_TODO_LOADING',
};
